// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbUxp-Cw5ANm5x9xbPexrymL1z1y0w2XE',
    appId: '1:1062952966879:web:482921d7ec5aa3f906a76a',
    messagingSenderId: '1062952966879',
    projectId: 'shamilapp-shamiltechnologies',
    authDomain: 'shamilapp-shamiltechnologies.firebaseapp.com',
    databaseURL: 'https://shamilapp-shamiltechnologies-default-rtdb.firebaseio.com',
    storageBucket: 'shamilapp-shamiltechnologies.firebasestorage.app',
    measurementId: 'G-52WSM84MQK',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo-5hmPwzGTbgvdXLWZkYJ1eh0ydo3dp0',
    appId: '1:1062952966879:ios:be2d47896a88848006a76a',
    messagingSenderId: '1062952966879',
    projectId: 'shamilapp-shamiltechnologies',
    databaseURL: 'https://shamilapp-shamiltechnologies-default-rtdb.firebaseio.com',
    storageBucket: 'shamilapp-shamiltechnologies.firebasestorage.app',
    iosBundleId: 'com.example.shamilWebApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbUxp-Cw5ANm5x9xbPexrymL1z1y0w2XE',
    appId: '1:1062952966879:web:7a9f8ffa8de53dae06a76a',
    messagingSenderId: '1062952966879',
    projectId: 'shamilapp-shamiltechnologies',
    authDomain: 'shamilapp-shamiltechnologies.firebaseapp.com',
    databaseURL: 'https://shamilapp-shamiltechnologies-default-rtdb.firebaseio.com',
    storageBucket: 'shamilapp-shamiltechnologies.firebasestorage.app',
    measurementId: 'G-D774M2YY4Q',
  );
}
